environment_id: ALE/Pong-v5
protocol_version: 1
training_agent_steps: 50000000
training_raw_ale_frames: 200000000
environment: {frameskip: 4, repeat_action_probability: 0.0, full_action_space: false, no_op_max: 30, screen_size: 84, grayscale_observation: true, frame_stack: 4, terminal_on_life_loss: true}
training: {gamma: 0.99, learning_rate: 0.00025, optimizer: rmsprop, rmsprop_alpha: 0.95, rmsprop_epsilon: 0.01, rmsprop_momentum: 0.95, replay_buffer_size: 1000000, learning_starts_agent_steps: 50000, train_frequency_agent_steps: 4, gradient_steps: 1, batch_size: 32, target_network_update_agent_steps: 40000, exploration_initial_epsilon: 1.0, exploration_final_epsilon: 0.1, exploration_duration_agent_steps: 1000000, reward_clip: [-1.0, 1.0]}
evaluation: {epsilon: 0.05, max_raw_ale_frames: 18000, no_op_max: 30}
